\begin{tabular}{|l|*{9}{c|}}
\hline
&\textbf{037}&\textbf{038}&\textbf{039}&\textbf{03A}&\textbf{03B}&\textbf{03C}&\textbf{03D}&\textbf{03E}&\textbf{03F}\\
\hline
\textbf{0}&
\utfchar{Ͱ}{ 370}&\utfchar{΀}{ 380}&\utfchar{ΐ}{ 390}&\utfchar{Π}{ 3a0}&\utfchar{ΰ}{ 3b0}&\utfchar{π}{ 3c0}&\utfchar{ϐ}{ 3d0}&\utfchar{Ϡ}{ 3e0}&\utfchar{ϰ}{ 3f0}\\
\hline
\textbf{1}&
\utfchar{ͱ}{ 371}&\utfchar{΁}{ 381}&\utfchar{Α}{ 391}&\utfchar{Ρ}{ 3a1}&\utfchar{α}{ 3b1}&\utfchar{ρ}{ 3c1}&\utfchar{ϑ}{ 3d1}&\utfchar{ϡ}{ 3e1}&\utfchar{ϱ}{ 3f1}\\
\hline
\textbf{2}&
\utfchar{Ͳ}{ 372}&\utfchar{΂}{ 382}&\utfchar{Β}{ 392}&\utfchar{΢}{ 3a2}&\utfchar{β}{ 3b2}&\utfchar{ς}{ 3c2}&\utfchar{ϒ}{ 3d2}&\utfchar{Ϣ}{ 3e2}&\utfchar{ϲ}{ 3f2}\\
\hline
\textbf{3}&
\utfchar{ͳ}{ 373}&\utfchar{΃}{ 383}&\utfchar{Γ}{ 393}&\utfchar{Σ}{ 3a3}&\utfchar{γ}{ 3b3}&\utfchar{σ}{ 3c3}&\utfchar{ϓ}{ 3d3}&\utfchar{ϣ}{ 3e3}&\utfchar{ϳ}{ 3f3}\\
\hline
\textbf{4}&
\utfchar{ʹ}{ 374}&\utfchar{΄}{ 384}&\utfchar{Δ}{ 394}&\utfchar{Τ}{ 3a4}&\utfchar{δ}{ 3b4}&\utfchar{τ}{ 3c4}&\utfchar{ϔ}{ 3d4}&\utfchar{Ϥ}{ 3e4}&\utfchar{ϴ}{ 3f4}\\
\hline
\textbf{5}&
\utfchar{͵}{ 375}&\utfchar{΅}{ 385}&\utfchar{Ε}{ 395}&\utfchar{Υ}{ 3a5}&\utfchar{ε}{ 3b5}&\utfchar{υ}{ 3c5}&\utfchar{ϕ}{ 3d5}&\utfchar{ϥ}{ 3e5}&\utfchar{ϵ}{ 3f5}\\
\hline
\textbf{6}&
\utfchar{Ͷ}{ 376}&\utfchar{Ά}{ 386}&\utfchar{Ζ}{ 396}&\utfchar{Φ}{ 3a6}&\utfchar{ζ}{ 3b6}&\utfchar{φ}{ 3c6}&\utfchar{ϖ}{ 3d6}&\utfchar{Ϧ}{ 3e6}&\utfchar{϶}{ 3f6}\\
\hline
\textbf{7}&
\utfchar{ͷ}{ 377}&\utfchar{·}{ 387}&\utfchar{Η}{ 397}&\utfchar{Χ}{ 3a7}&\utfchar{η}{ 3b7}&\utfchar{χ}{ 3c7}&\utfchar{ϗ}{ 3d7}&\utfchar{ϧ}{ 3e7}&\utfchar{Ϸ}{ 3f7}\\
\hline
\textbf{8}&
\utfchar{͸}{ 378}&\utfchar{Έ}{ 388}&\utfchar{Θ}{ 398}&\utfchar{Ψ}{ 3a8}&\utfchar{θ}{ 3b8}&\utfchar{ψ}{ 3c8}&\utfchar{Ϙ}{ 3d8}&\utfchar{Ϩ}{ 3e8}&\utfchar{ϸ}{ 3f8}\\
\hline
\textbf{9}&
\utfchar{͹}{ 379}&\utfchar{Ή}{ 389}&\utfchar{Ι}{ 399}&\utfchar{Ω}{ 3a9}&\utfchar{ι}{ 3b9}&\utfchar{ω}{ 3c9}&\utfchar{ϙ}{ 3d9}&\utfchar{ϩ}{ 3e9}&\utfchar{Ϲ}{ 3f9}\\
\hline
\textbf{A}&
\utfchar{ͺ}{ 37a}&\utfchar{Ί}{ 38a}&\utfchar{Κ}{ 39a}&\utfchar{Ϊ}{ 3aa}&\utfchar{κ}{ 3ba}&\utfchar{ϊ}{ 3ca}&\utfchar{Ϛ}{ 3da}&\utfchar{Ϫ}{ 3ea}&\utfchar{Ϻ}{ 3fa}\\
\hline
\textbf{B}&
\utfchar{ͻ}{ 37b}&\utfchar{΋}{ 38b}&\utfchar{Λ}{ 39b}&\utfchar{Ϋ}{ 3ab}&\utfchar{λ}{ 3bb}&\utfchar{ϋ}{ 3cb}&\utfchar{ϛ}{ 3db}&\utfchar{ϫ}{ 3eb}&\utfchar{ϻ}{ 3fb}\\
\hline
\textbf{C}&
\utfchar{ͼ}{ 37c}&\utfchar{Ό}{ 38c}&\utfchar{Μ}{ 39c}&\utfchar{ά}{ 3ac}&\utfchar{μ}{ 3bc}&\utfchar{ό}{ 3cc}&\utfchar{Ϝ}{ 3dc}&\utfchar{Ϭ}{ 3ec}&\utfchar{ϼ}{ 3fc}\\
\hline
\textbf{D}&
\utfchar{ͽ}{ 37d}&\utfchar{΍}{ 38d}&\utfchar{Ν}{ 39d}&\utfchar{έ}{ 3ad}&\utfchar{ν}{ 3bd}&\utfchar{ύ}{ 3cd}&\utfchar{ϝ}{ 3dd}&\utfchar{ϭ}{ 3ed}&\utfchar{Ͻ}{ 3fd}\\
\hline
\textbf{E}&
\utfchar{;}{ 37e}&\utfchar{Ύ}{ 38e}&\utfchar{Ξ}{ 39e}&\utfchar{ή}{ 3ae}&\utfchar{ξ}{ 3be}&\utfchar{ώ}{ 3ce}&\utfchar{Ϟ}{ 3de}&\utfchar{Ϯ}{ 3ee}&\utfchar{Ͼ}{ 3fe}\\
\hline
\textbf{F}&
\utfchar{Ϳ}{ 37f}&\utfchar{Ώ}{ 38f}&\utfchar{Ο}{ 39f}&\utfchar{ί}{ 3af}&\utfchar{ο}{ 3bf}&\utfchar{Ϗ}{ 3cf}&\utfchar{ϟ}{ 3df}&\utfchar{ϯ}{ 3ef}&\utfchar{Ͽ}{ 3ff}\\
\hline
\end{tabular}
